# Site settings
title: Tanya Fesenko
twitter_username: tanya_fesenko
name: Tanya Fesenko

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://tfesenko.com/
 - title: GitHub
   url: https://github.com/tfesenko
 - title: LinkedIn
   url: https://www.linkedin.com/pub/rob-hinds/21/361/3b1

#Any buzzword skills you want to include
skills:
 - Java
 - Eclipse RCP
 - REST
 - EMF
 - Xtext


#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://tfesenko.com/feed/

#Work experience is required
roles:
 - title: Senior software developer and team leader
   start: 2011
   end: Ongoing
   employer: ModelSolv, Inc.
   description: I was the first programmer to work for ModelSolv. Since the time of my joining, the company now engages a global development team ranging in size from 5 to 8. I am developing an application for model interchange, the application already had three releases. My work includes software development, remote and onsite communication with the client on daily basis and managing the core team.
 - title: Research engineer
   start: 2010
   end: 2011
   employer: CEA LIST, France (http://www-list.cea.fr/)
   description: My area of responsibility included the SysML Block Definition diagram editor, containment link implementation and advanced new diagram wizard. A month after joining CEA I became a representative and contributor of CEA at Eclipse Foundation as a committer at MDT project.
 - title: Sr. R&D engineer(Java) 
   start: 2006
   end: 2010
   employer: Prague branch of Borland Software Corp., Czech Republic (www.borland.com)
   description: My roles included a developer, presenter (two speeches at EclipseCon 2008 at Santa Clara: one-hour tutorial, ten-minute talk), technical writer (wikipedia), customer support (answering newsgroup) and manager (reviewing requests, requirement analysis, writing reports).
 - title: R&D engineer (Java)
   start: 2003
   end: 2006
   employer: St. Petersburg branch of Borland Software Corp., Russia (www.borland.com)
   description: BPMN diagram editor and BPEL export. Implementation of requirements management tools (RequisitePro & CaliberRM) and Together Designer integration, DOORS integration with Together Control Center, Design Pattern recognition prototype.
   
   
#Education is required
education:
 - level: BMaster of Computer Science (graduated with honors)
   date: 2005
   subject: Mathematics and Computer Science
   school: Saint-Petersburg State University, Russia (http://www.eng.spbu.ru/university/today/)

#This section is optional (as is the image link below)
# TODO Coursera does not publish completed courses in a publicly available form
# TODO add other certificates
coursera:
   profileurl: https://www.coursera.org/
   courses:
    - title: Fundamentals of Project Planning and Management by University of Virginia on Coursera.
      link: https://www.coursera.org/account/accomplishments/certificate/ARSZGHBDBAV8
      date: December 3, 2016


#List of interesting Github repo/projects to include - optional
github:
 - RepreZen/SwagEdit

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/2068744/tanya
   flairimageurl: http://stackoverflow.com/users/flair/2068744.png


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others.  In my current role Groovy is the primary language used - and I am familiar with many of the languages features and quirks (including writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>). <br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC framework (although current role uses ColdFusion for server side web stack). I have also worked with some client side technology, having used jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
